MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no 
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
VIA_ENABLE = yes

RGBLIGHT_ENABLE = yes

# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = WS2812
# RGB_MATRIX_CUSTOM_USER = no //only need this if using custom effects